server:
  port: 8082
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
  datasource:
    url: jdbc:mysql://localhost:3306/hivantibodyscreening?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: HAD.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
